name: Update version number

on:
  push:
    branches: [ main ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update version number
        run: |
          # Find the current version number in the code
          CURRENT_VERSION=$(grep 'define.*VERSION' version.php | sed -E 's/.*"(.*)".*/\1/')

          # Increment the version number by one
          NEW_VERSION=$(php -r "echo implode('.', array_slice(explode('.', '$CURRENT_VERSION'), 0, 2)).'.'.((int)end(explode('.', '$CURRENT_VERSION')) + 1);")

          # Replace the current version number with the new version number
          sed -i "s/define('VERSION', '$CURRENT_VERSION');/define('VERSION', '$NEW_VERSION');/" version.php

      - name: Commit changes
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git commit -am "Update version number"
          git push
