name: Update version number

on:
  push:
    branches: [ main ]

jobs:
  update_code:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Update code
      run: |
        php update_version.php
        git config user.email "github-actions@github.com"
        git config user.name "Github Actions"
        git add .
        git commit -m "Update code"
        git push origin main
