name: Version Update

on:
  push:
    branches:
      - main

jobs:
  version_update:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout code
      uses: actions/checkout@v2
    - name: Version Update
      run: |
        php version_update.php
        git config user.email "github-actions@github.com"
        git config user.name "GitHub Actions"
        git add.
        git commit -m "Version Update"
        git push origin main
